In [3]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [6]:
data = np.asarray([['red'],['green'],['blue']])

In [7]:
encoder = OrdinalEncoder()

In [9]:
result = encoder.fit_transform(data) 

In [10]:
print(result)  ##it has ordered the data based on alphabetical order so blue was given 0 and green give 1 

[[2.]
 [1.]
 [0.]]


In [11]:
from sklearn.preprocessing import LabelEncoder 

In [27]:
l_encoder = LabelEncoder()

In [28]:
lresult = l_encoder.fit_transform(data) 

C:\Users\T\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
print(lresult) 

[2 1 0]


In [25]:
car_df = pd.read_csv('cardata.csv')

In [16]:
car_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [18]:
car_df.describe(include='object')

Make           Model  Engine Fuel Type Transmission Type  \
count       11914           11914             11911             11914   
unique         48             915                10                 5   
top     Chevrolet  Silverado 1500  regular unleaded         AUTOMATIC   
freq         1123             156              7172              8266   

            Driven_Wheels Market Category Vehicle Size Vehicle Style  
count               11914            8172        11914         11914  
unique                  4              71            3            16  
top     front wheel drive       Crossover      Compact         Sedan  
freq                 4787            1110         4764          3048

In [19]:
car_df['Engine Fuel Type'].unique()

array(['premium unleaded (required)', 'regular unleaded',
       'premium unleaded (recommended)', 'flex-fuel (unleaded/E85)',
       'diesel', 'electric',
       'flex-fuel (premium unleaded recommended/E85)', 'natural gas',
       'flex-fuel (premium unleaded required/E85)',
       'flex-fuel (unleaded/natural gas)', nan], dtype=object)

In [29]:
car_df['Engine Fuel Type Encoded']=l_encoder.fit_transform(car_df['Engine Fuel Type']) ##make sure to use the underscore in label encoder




In [30]:
car_df['Engine Fuel Type'].unique()  ###now they have labels 

array([ 8,  9,  7,  4,  0,  1,  2,  6,  3,  5, 10])

In [33]:
car_df.describe(include='object')  ###no longer in the object category because its now an integer   ###you need to keep track of what the numbers represent.


##alternatively you could engineer a feature  a new column with the data encoded -- code below 

##car_df['Engine Fuel Type Encoded']=l_encoder.fit_transform(car_df['Engine Fuel Type']) ##make sure to use the underscore in label encoder


#l_encoder.inverse_transform(car_df['Engine Fuel Type'])  --> this will transform the data to its origninal format

Make           Model Transmission Type      Driven_Wheels  \
count       11914           11914             11914              11914   
unique         48             915                 5                  4   
top     Chevrolet  Silverado 1500         AUTOMATIC  front wheel drive   
freq         1123             156              8266               4787   

       Market Category Vehicle Size Vehicle Style  
count             8172        11914         11914  
unique              71            3            16  
top          Crossover      Compact         Sedan  
freq              1110         4764          3048

In [32]:
##one hot encoder is used to prevent relationships being forced into the code

###issue is you get a very large dataset --> a dataset with high dimesionality 

In [34]:
from sklearn.preprocessing import OneHotEncoder   ###it doesn't like sparse data --data with lots of 0's

In [38]:
data = np.asarray([['red'],['green'],['blue']])

In [39]:
onehot = OneHotEncoder(sparse = False)

In [40]:
result = onehot.fit_transform(data)

C:\Users\T\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [43]:
data

array([['red'],
       ['green'],
       ['blue']], dtype='<U5')

In [42]:
print(result)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
car_df = pd.read_csv('cardata.csv')

In [45]:
onehot.fit_transform(car_df[['Engine Fuel Type']]) ##the extra brackets makes it a 2d array it was previously a 1D array onehotencoder requires a 2D array

C:\Users\T\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

Engine Fuel Type
0                 8
1                 8
2                 8
3                 8
4                 8

In [ ]:
###one hot for when you don't want to create artifical relationships

##ordinal ##matrix data

##label 1 fgeature data that you want order to

In [47]:
sample = ['The weather is nice', 
          'Hot weather', 
          'its nice that the weather is hot']

In [48]:
from sklearn.feature_extraction.text import CountVectorizer   ##works like onhotencoder 

In [49]:
vec = CountVectorizer()
X=vec.fit_transform(sample)   ###the vec is the algorithim the fit transform will do the transformation 

In [52]:
pd.DataFrame(X.toarray(),columns=vec.get_feature_names_out())  ##X is the data that we have transformed to an array and the get feature names is pulling each word and making it a column

##get_feature_names is the old version of sckitlearn so I used get_feature_names_out because it is the new version.

hot  is  its  nice  that  the  weather
0    0   1    0     1     0    1        1
1    1   0    0     0     0    0        1
2    1   1    1     1     1    1        1

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
vec = TfidfVectorizer()  #####tfidf is giving a frequency  sometimes a bias can happen when it comes to large numbers so using frequency may be bettter its a probability of a number appearing


X=vec.fit_transform(sample) 

###all choice have pros and cons -- study the data then start to make decisions regarding the data for the machine elaring alogorithm 

In [57]:
pd.DataFrame(X.toarray(),columns=vec.get_feature_names_out())

hot        is       its      nice      that       the   weather
0  0.000000  0.526820  0.000000  0.526820  0.000000  0.526820  0.409123
1  0.789807  0.000000  0.000000  0.000000  0.000000  0.000000  0.613356
2  0.352215  0.352215  0.463121  0.352215  0.463121  0.352215  0.273526

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.array([1,2,3,4,5])